#!/usr/bin/env python3
"""Write the boot module graph into site/index.html as <link rel="modulepreload"> lines.

WHY (#284, measured 2026-09-27). There is no bundler, and every /js/** module is served
`no-cache`, so the browser found the graph one import level at a time: main.js, then what it
imports, then what those import -- a waterfall of revalidations about a dozen levels deep. A
modulepreload line per module lets the browser ask for all of them at once while it parses the
HTML. The graph is the STATIC imports reachable from site/js/main.js; a dynamic import() stays
lazy, which is the point of it.

    python3 scripts/gen_modulepreload.py           # rewrite the block
    python3 scripts/gen_modulepreload.py --check   # exit 1 if it is stale (tests/test_contract.mjs checks too)
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SITE = ROOT / "site"
ENTRY = SITE / "js" / "main.js"
HTML = SITE / "index.html"
BEGIN = "<!-- MODULEPRELOAD:BEGIN generated by scripts/gen_modulepreload.py; do not edit -->"
END = "<!-- MODULEPRELOAD:END -->"

# `import x from './a.js'`, `import {a} from"./b.js"` (minified vendor), `export * from './c.js'`,
# and the bare side-effect form `import './d.js'`. Not `import(` -- that one is lazy on purpose.
STATIC = re.compile(r"""(?:\bimport|\bexport)\s*(?:[^'";()]*?\bfrom\s*)?['"](\.{1,2}/[^'"]+)['"]""")


def graph(entry: Path) -> list:
    seen = []
    todo = [entry.resolve()]
    while todo:
        path = todo.pop(0)
        if path in seen or not path.exists():
            continue
        seen.append(path)
        text = path.read_text(encoding="utf-8")
        for spec in STATIC.findall(text):
            todo.append((path.parent / spec).resolve())
    return sorted(seen, key=lambda p: p.relative_to(SITE).as_posix())


# THE LIGHT EMBED (internal #396, 2026-10-07). `?embed=1&at=moon` boots js/embedlite.js and never asks
# for main.js, but a <link rel="modulepreload"> in the page is fetched whatever the address says:
# 112 modules, 2.2 MB, for a frame that draws one object. So the lines sit in a <template>, where a
# browser neither fetches nor preloads them, and the one-line script after it moves them into the
# <head> at once unless the address is an embed's. A normal visit asks for them at the same point
# of the parse as before. The page's boot script moves them itself when an embed turns out to need
# the whole app after all.
TEMPLATE_OPEN = '<template id="sr-preload">'
TEMPLATE_CLOSE = '</template>'
ACTIVATE = ("<script>if(!/[?&]embed=1(?:&|$)/.test(location.search))"
            "document.head.appendChild(document.getElementById('sr-preload').content)</script>")


def block() -> str:
    lines = [BEGIN, TEMPLATE_OPEN]
    for path in graph(ENTRY):
        lines.append(f'<link rel="modulepreload" href="{path.relative_to(SITE).as_posix()}">')
    lines += [TEMPLATE_CLOSE, ACTIVATE, END]
    return "\n".join(lines)


def render(html: str) -> str:
    new = block()
    if BEGIN in html and END in html:
        start = html.index(BEGIN)
        stop = html.index(END) + len(END)
        return html[:start] + new + html[stop:]
    return html.replace("</head>", new + "\n</head>", 1)


def main() -> int:
    html = HTML.read_text(encoding="utf-8")
    out = render(html)
    n = out.count('rel="modulepreload"')
    if "--check" in sys.argv:
        if out != html:
            print("modulepreload: site/index.html is stale; run python3 scripts/gen_modulepreload.py")
            return 1
        print(f"modulepreload ok: {n} modules in the boot graph")
        return 0
    HTML.write_text(out, encoding="utf-8")
    print(f"modulepreload: wrote {n} modules")
    return 0


if __name__ == "__main__":
    sys.exit(main())
