#!/usr/bin/env python3
"""Write the home page's search and preview tags into site/index.html (spec 0061 task 9).

WHAT IS IN THE BLOCK. The title and description a search result shows, the canonical URL, the Open
Graph and Twitter Card tags a chat or a feed shows for a shared link to the root, `theme-color`,
and one JSON-LD script: a `WebSite`, and a `Dataset` for the live layers whose `isBasedOn` lists
every upstream in registry/sources.yaml, by its own attribution line, with the licence where that
line names one. Generated, because the list of sources changes with a registry row and a hand-kept
copy of it would drift the way the trip pages would without their generator.

NO SearchAction. A sitelinks search box needs a URL that runs a search, and the app has none:
ui/urlstate.js KEYS has no `q`, and `#at=` resolves a name to one object rather than listing
results. Pointing a SearchAction at `#at=` would promise a search the page does not do.

THE BYTES. This block is on the home page's first visit, so it is kept to the tags a crawler or an
unfurler reads, on one line each, and the JSON-LD is written without spaces.

    python3 scripts/gen_home_seo.py           # rewrite the block
    python3 scripts/gen_home_seo.py --check   # exit 1 if it is stale
"""

from __future__ import annotations

import html
import json
import re
import sys
from pathlib import Path
from urllib.parse import urlsplit

import yaml

ROOT = Path(__file__).resolve().parent.parent
HTML = ROOT / "site" / "index.html"
SOURCES = ROOT / "registry" / "sources.yaml"
BEGIN = "<!-- SEO:BEGIN generated by scripts/gen_home_seo.py; do not edit -->"
END = "<!-- SEO:END -->"

HOST = "https://www.spaceradar.ai"
REPO = "https://github.com/Sara-Managed-Projects/space-radar"
NAME = "Space Radar"
TITLE = "Space Radar: live 3D map of satellites, planets and stars"
DESCRIPTION = ("A live 3D map of space: satellites and the ISS, launches, probes, planets, stars and "
               "galaxies, each drawn where it really is, with where the numbers come from.")
# What a shared link to the root says (spec 0033), unchanged.
OG_DESCRIPTION = "Everything in motion around Earth, where it really is, right now."
OG_IMAGE_ALT = "The Earth from space with the satellites around it as points of light, captioned Space Radar."
DATASET_NAME = "Space Radar live layers"
DATASET_DESCRIPTION = ("Where satellites, stations, launches, probes, asteroids and comets are, read from "
                       "the public sources it is based on when the map opens.")

LICENCES = {
    "CC BY 4.0": "https://creativecommons.org/licenses/by/4.0/",
    "CC0": "https://creativecommons.org/publicdomain/zero/1.0/",
}


def based_on() -> list:
    """One entry per upstream host: its address, and where the attribution names a licence, the
    licence with it. Addresses alone keep the block small; the names are in the app's Sources panel,
    and the licence is the part a reuser needs."""
    doc = yaml.safe_load(SOURCES.read_text(encoding="utf-8")) or {}
    out: dict[str, object] = {}
    for row in doc.get("sources") or []:
        if row.get("enabled") is False:
            continue
        parts = urlsplit(str(row.get("url") or ""))
        origin = f"{parts.scheme}://{parts.netloc}/"
        if origin in out:
            continue
        name = str(row.get("attribution") or "").strip()
        licence = next((url for key, url in LICENCES.items() if f"({key})" in name), None)
        out[origin] = {"@type": "Dataset", "url": origin, "license": licence} if licence else origin
    return list(out.values())


def block() -> str:
    ld = {"@context": "https://schema.org", "@graph": [
        {"@type": "WebSite", "@id": f"{HOST}/#website", "url": f"{HOST}/", "name": NAME,
         "inLanguage": "en"},
        {"@type": "Dataset", "name": DATASET_NAME, "description": DATASET_DESCRIPTION, "url": f"{HOST}/",
         "isAccessibleForFree": True, "creator": {"@type": "Organization", "name": f"{NAME} contributors",
                                                   "url": REPO},
         "isBasedOn": based_on()},
    ]}
    e = lambda s: html.escape(s, quote=True)  # noqa: E731
    lines = [
        BEGIN,
        f"<title>{e(TITLE)}</title>",
        f'<meta name="description" content="{e(DESCRIPTION)}">',
        f'<link rel="canonical" href="{HOST}/">',
        '<meta name="theme-color" content="#0b0e14">',
        '<meta property="og:type" content="website">',
        f'<meta property="og:site_name" content="{NAME}">',
        f'<meta property="og:title" content="{NAME}">',
        f'<meta property="og:description" content="{e(OG_DESCRIPTION)}">',
        f'<meta property="og:image" content="{HOST}/og/default.png">',
        '<meta property="og:image:width" content="1200">',
        '<meta property="og:image:height" content="630">',
        f'<meta property="og:image:alt" content="{e(OG_IMAGE_ALT)}">',
        f'<meta property="og:url" content="{HOST}/">',
        '<meta name="twitter:card" content="summary_large_image">',
        '<script type="application/ld+json">'
        + json.dumps(ld, ensure_ascii=False, separators=(",", ":")).replace("</", "<\\/") + "</script>",
        END,
    ]
    return "\n".join(lines)


def rewrite(text: str) -> str:
    pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
    if not pattern.search(text):
        raise SystemExit(f"gen_home_seo: {HTML.relative_to(ROOT)} has no {BEGIN!r} block")
    return pattern.sub(lambda _: block(), text, count=1)


def main(argv: list[str]) -> int:
    check = "--check" in argv
    current = HTML.read_text(encoding="utf-8")
    want = rewrite(current)
    if check:
        if want == current:
            print("the home page's search and preview tags are current")
            return 0
        print(f"{HTML.relative_to(ROOT)}: the SEO block is STALE (registry/sources.yaml or the words changed).\n"
              f"  Run: python3 scripts/{Path(sys.argv[0]).name}")
        return 1
    if want != current:
        HTML.write_text(want, encoding="utf-8")
        print(f"wrote the SEO block in {HTML.relative_to(ROOT)}")
    else:
        print("the SEO block is already current")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
