#!/usr/bin/env python3
"""Render every trip stop's words to speech, offline, and refuse when the files have drifted.

Spec 0069 (2026-10-03). Ivan: "Speech for trips (like in planetarium ...), we will need the best
free speech generator, we will regenerate all speeches and download them." So the voice is made
HERE, once, by a model whose licence lets the files ship (registry/narration.yaml says which and
why), and the browser only ever plays a file: nothing is synthesised on a visitor's device and
nothing is fetched before they turn sound on (spec 0035 req 1).

    python3 scripts/narrate.py --check                      # CI: no TTS, stdlib + PyYAML
    $VENV/bin/python scripts/narrate.py --models DIR        # render what is stale
    $VENV/bin/python scripts/narrate.py --models DIR --only to-the-edge/sirius --force
    $VENV/bin/python scripts/narrate.py --models DIR --audition OUT --voices bf_emma,bm_george

WHAT IS SPOKEN. The stop's card, as the visitor reads it: the title, then the body. The bodies are
written to follow their titles ("A rover driven from Earth" / "Nobody rode it."), so the body
alone is often a sentence with no subject. registry/narration.yaml may leave a title out
(`skip_title`) where the body repeats it, or replace a stop's words for the ear (`say`).

WRITTEN FOR THE EYE, READ FOR THE EAR. spoken() turns what a synthesiser trips on into words --
"109 389" (a thin-spaced number), "3 February 1966", "10 km", "0.12", "M87", "TRAPPIST-1" -- and
REFUSES a digit it does not know how to say, rather than leaving the model to guess. Names the
grapheme-to-phoneme step gets wrong are in the registry's `lexicon`, as phonemes.

ONE CLIP PER STOP, ONE CUE PER SENTENCE. Each sentence is synthesised on its own and the clip is
the sentences joined with pauses this script chooses, so the WebVTT timings are sample counts and
not an aligner's guess. Levelled to -16 LUFS (a gain and a peak limiter, encode() says why), then
Opus at 32 kbps mono and an AAC twin for a Safari that cannot decode Opus (audio/pick.js).

IDEMPOTENT BY HASH. A clip's hash is its spoken script, the voice, the speed, the engine's id and
the pauses. A stop whose hash is in the manifest and whose files are there is left alone; change a
card's words and --check fails until that one stop is rendered again.

The render needs: kokoro-onnx, misaki[en], soundfile, numpy, PyYAML, an ffmpeg with libopus, and
the two model files (kokoro-v1.0.onnx, voices-v1.0.bin) whose sha256 the registry records.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
REGISTRY = ROOT / "registry" / "narration.yaml"
TOURS = ROOT / "registry" / "tours.yaml"
BUDGETS = ROOT / "registry" / "budgets.yaml"
OUT = ROOT / "site" / "audio" / "narration"
MARK = "# ---- GENERATED BY scripts/narrate.py BELOW THIS LINE. Do not edit. ----"

# ------------------------------------------------------------------------------- numbers as words

ONES = ("zero one two three four five six seven eight nine ten eleven twelve thirteen fourteen "
        "fifteen sixteen seventeen eighteen nineteen").split()
TENS = "- - twenty thirty forty fifty sixty seventy eighty ninety".split()
ORDINALS = {
    1: "first", 2: "second", 3: "third", 4: "fourth", 5: "fifth", 6: "sixth", 7: "seventh",
    8: "eighth", 9: "ninth", 10: "tenth", 11: "eleventh", 12: "twelfth", 13: "thirteenth",
    14: "fourteenth", 15: "fifteenth", 16: "sixteenth", 17: "seventeenth", 18: "eighteenth",
    19: "nineteenth", 20: "twentieth", 30: "thirtieth",
}
MONTHS = ("January February March April May June July August September October November "
          "December").split()
UNITS = {"km": "kilometres", "m": "metres", "kg": "kilograms"}
SPACES = "\u00a0\u2009\u202f"


def int_words(n: int) -> str:
    """British: "one hundred and nine thousand three hundred and eighty-nine"."""
    if n < 0:
        return "minus " + int_words(-n)
    if n < 20:
        return ONES[n]
    if n < 100:
        return TENS[n // 10] + ("-" + ONES[n % 10] if n % 10 else "")
    if n < 1000:
        rest = n % 100
        return ONES[n // 100] + " hundred" + (" and " + int_words(rest) if rest else "")
    for size, name in ((10 ** 9, "billion"), (10 ** 6, "million"), (1000, "thousand")):
        if n >= size:
            head, rest = divmod(n, size)
            if not rest:
                return f"{int_words(head)} {name}"
            joiner = " and " if rest < 100 else " "
            return f"{int_words(head)} {name}{joiner}{int_words(rest)}"
    raise ValueError(n)


def ordinal_words(n: int) -> str:
    if n in ORDINALS:
        return ORDINALS[n]
    return TENS[n // 10] + "-" + ORDINALS[n % 10]


def year_words(y: int) -> str:
    """1966 -> nineteen sixty-six, 2005 -> two thousand and five, 2030 -> twenty thirty."""
    if 2000 <= y <= 2009:
        return "two thousand" + (" and " + ONES[y % 10] if y % 10 else "")
    head, tail = divmod(y, 100)
    if tail == 0:
        return int_words(head) + " hundred"
    if tail < 10:
        return f"{int_words(head)} oh {ONES[tail]}"
    return f"{int_words(head)} {int_words(tail)}"


def decimal_words(text: str) -> str:
    whole, frac = text.split(".")
    head = "nought" if int(whole) == 0 else int_words(int(whole))
    return head + " point " + " ".join(ONES[int(d)] for d in frac)


def number_words(text: str) -> str:
    return decimal_words(text) if "." in text else int_words(int(text))


def spoken(text: str) -> str:
    """The words a voice says for `text`. Pure and stdlib only: --check runs it with no TTS."""
    s = str(text)
    for ch in SPACES:
        s = s.replace(ch, " ")
    # "109 389": digit groups a typographer spaced. Said at once, so the year rule below never
    # sees "6 332" as a count followed by a year.
    s = re.sub(r"(?<![\d.])\d{1,3}(?: \d{3})+(?![\d.])", lambda m: int_words(int(m.group(0).replace(" ", ""))), s)
    # "3 February 1966" -> "the third of February 1966" (the year is said by the year rule).
    s = re.sub(r"\b(\d{1,2}) (%s)\b" % "|".join(MONTHS),
               lambda m: f"the {ordinal_words(int(m.group(1)))} of {m.group(2)}", s)
    # "TRAPPIST-1", "IM-2", "Chandrayaan-2", "560-year": the hyphen is not a minus.
    s = re.sub(r"(?<=[A-Za-z])-(?=\d)", " ", s)
    s = re.sub(r"(?<=\d)-(?=[A-Za-z])", " ", s)
    # "M87" is "M eighty-seven".
    s = re.sub(r"\b([A-Z]+)(\d+)\b", r"\1 \2", s)
    # "10 km", "3.4 m", "1 kg".
    def unit(m):
        word = UNITS[m.group(2)]
        return number_words(m.group(1)) + " " + (word[:-1] if m.group(1) == "1" else word)
    s = re.sub(r"\b(\d+(?:\.\d+)?) (km|kg|m)\b", unit, s)
    s = re.sub(r"\b\d+\.\d+\b", lambda m: decimal_words(m.group(0)), s)
    s = re.sub(r"\b(1[5-9]\d\d|20\d\d)\b", lambda m: year_words(int(m.group(1))), s)
    s = re.sub(r"\b\d+\b", lambda m: int_words(int(m.group(0))), s)
    s = re.sub(r"\s+", " ", s).strip()
    left = re.search(r"[\d%°+=<>&@#/\\{}_]", s)
    if left:
        raise ValueError(f"spoken(): do not know how to say {left.group(0)!r} in {text!r}; "
                         f"teach scripts/narrate.py or give the stop a `say:` in registry/narration.yaml")
    return s


def sentences(text: str) -> list:
    """Split where a reader breathes: after . ! ? before a capital. "3.4 m" and "It says: This" hold."""
    parts = re.split(r"(?<=[.!?])\s+(?=[A-Z\"'(\d])", str(text).strip())
    return [p.strip() for p in parts if p.strip()]


# ------------------------------------------------------------------------------ the script of a stop

def load_config() -> tuple:
    raw = REGISTRY.read_text(encoding="utf-8")
    head = raw.split(MARK)[0]
    doc = yaml.safe_load(raw) or {}
    return head, doc


def load_tours() -> list:
    """The trips, with each card as the browser shows it: gen_tours_js.py fills `{exoplanet_count}`
    from the catalogue, and a voice that read the placeholder aloud would say "exoplanet count"."""
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from gen_tours_js import expand_card

    tours = (yaml.safe_load(TOURS.read_text(encoding="utf-8")) or {}).get("tours") or []
    for trip in tours:
        for stop in trip.get("stops") or []:
            if isinstance(stop.get("card"), dict) and stop["card"].get("body"):
                stop["card"] = expand_card(stop["card"])
    return tours


def apply_lexicon(text: str, lexicon: dict) -> str:
    """Wrap each lexicon word in the G2P's own markup: [Tiangong](/phonemes/)."""
    out = text
    for word in sorted(lexicon or {}, key=len, reverse=True):
        out = re.sub(r"(?<![\w\[])%s(?![\w\]])" % re.escape(word), f"[{word}](/{lexicon[word]}/)", out)
    return out


def cues_for(trip: dict, stop: dict, cfg: dict) -> list:
    """[(what the caption shows, what the voice is given)] for one stop, in order."""
    key = f"{trip['id']}/{stop['id']}"
    card = stop.get("card") or {}
    say = (cfg.get("say") or {}).get(key)
    shown = []
    if say:
        shown = sentences(say)
    else:
        title = str(card.get("title") or "").strip()
        if title and key not in (cfg.get("skip_title") or []):
            shown.append(title if title[-1] in ".!?" else title + ".")
        shown.extend(sentences(card.get("body") or ""))
    lexicon = cfg.get("lexicon") or {}
    return [(text, apply_lexicon(spoken(text), lexicon)) for text in shown]


def clip_hash(cues: list, cfg: dict) -> str:
    voice = cfg.get("voice") or {}
    payload = [
        (cfg.get("engine") or {}).get("id"), voice.get("id"), voice.get("lang"), voice.get("speed"),
        cfg.get("timing"), cfg.get("encode"), [spoken_text for _, spoken_text in cues],
    ]
    blob = json.dumps(payload, ensure_ascii=False, sort_keys=True).encode("utf-8")
    return hashlib.sha256(blob).hexdigest()[:16]


def word_count(cues: list) -> int:
    plain = " ".join(re.sub(r"\[([^\]]+)\]\(/[^)]*/\)", r"\1", s) for _, s in cues)
    return len(re.findall(r"[A-Za-z']+(?:-[A-Za-z']+)*", plain))


def every_stop(tours: list):
    for trip in tours:
        for stop in trip.get("stops") or []:
            yield trip, stop


# ------------------------------------------------------------------------------------- the files

def paths(trip_id: str, stop_id: str) -> dict:
    base = OUT / trip_id
    return {ext: base / f"{stop_id}.{ext}" for ext in ("opus", "m4a", "vtt")}


def stamp(seconds: float) -> str:
    ms = int(round(seconds * 1000))
    return f"{ms // 60000:02d}:{(ms % 60000) // 1000:02d}.{ms % 1000:03d}"


def vtt_text(timed: list) -> str:
    lines = ["WEBVTT", ""]
    for start, end, text in timed:
        lines += [f"{stamp(start)} --> {stamp(end)}", text, ""]
    return "\n".join(lines)


def parse_vtt(text: str) -> list:
    out = []
    lines = text.splitlines()
    for i, line in enumerate(lines):
        m = re.match(r"(\d+):(\d+)\.(\d+) --> (\d+):(\d+)\.(\d+)", line)
        if m and i + 1 < len(lines):
            a = int(m.group(1)) * 60 + int(m.group(2)) + int(m.group(3)) / 1000
            b = int(m.group(4)) * 60 + int(m.group(5)) + int(m.group(6)) / 1000
            out.append((a, b, lines[i + 1]))
    return out


def budgets() -> dict:
    doc = yaml.safe_load(BUDGETS.read_text(encoding="utf-8")) or {}
    return {r["id"]: r["value"] for r in doc.get("budgets") or [] if isinstance(r, dict) and "id" in r}


def write_registry(head: str, clips: list) -> None:
    rows = "".join(
        "  - {" + ", ".join(f"{k}: {json.dumps(v, ensure_ascii=False)}" for k, v in row.items()) + "}\n"
        for row in clips
    )
    REGISTRY.write_text(head.rstrip("\n") + "\n" + MARK + "\nclips:\n" + rows, encoding="utf-8")


# -------------------------------------------------------------------------------------- --check

def check() -> int:
    _, cfg = load_config()
    tours = load_tours()
    rows = {f"{r['trip']}/{r['stop']}": r for r in cfg.get("clips") or []}
    gates = budgets()
    errors = []
    per_trip = {}
    total = 0
    seen = set()
    for trip, stop in every_stop(tours):
        key = f"{trip['id']}/{stop['id']}"
        seen.add(key)
        try:
            cues = cues_for(trip, stop, cfg)
        except ValueError as e:
            errors.append(str(e))
            continue
        row = rows.get(key)
        if not row:
            errors.append(f"{key}: no narration. Render it: scripts/narrate.py --models DIR --only {key}")
            continue
        if row.get("hash") != clip_hash(cues, cfg):
            errors.append(f"{key}: the card's words, the voice or the engine changed since this clip was "
                          f"rendered. Render it again: scripts/narrate.py --models DIR --only {key}")
        p = paths(trip["id"], stop["id"])
        for ext in ("opus", "m4a", "vtt"):
            if not p[ext].exists():
                errors.append(f"{key}: {p[ext].relative_to(ROOT)} is missing")
            elif p[ext].stat().st_size != row.get(ext):
                errors.append(f"{key}: {p[ext].relative_to(ROOT)} is {p[ext].stat().st_size} B, "
                              f"the manifest says {row.get(ext)}")
            else:
                total += row[ext]
        per_trip[trip["id"]] = per_trip.get(trip["id"], 0) + int(row.get("opus") or 0)
        if p["vtt"].exists():
            timed = parse_vtt(p["vtt"].read_text(encoding="utf-8"))
            if [t for _, _, t in timed] != [shown for shown, _ in cues]:
                errors.append(f"{key}: the captions are not the card's sentences")
            elif timed and timed[-1][1] > float(row.get("seconds") or 0) + 0.01:
                errors.append(f"{key}: the last caption ends after the clip does")
        wpm = float(row.get("words") or 0) / max(1e-6, float(row.get("seconds") or 0)) * 60
        lo, hi = (cfg.get("checks") or {}).get("wpm", [110, 200])
        if not lo <= wpm <= hi:
            errors.append(f"{key}: {wpm:.0f} words a minute is outside {lo}-{hi}: a clip that is silence, "
                          f"or one that was cut short")
    for key in rows:
        if key not in seen:
            errors.append(f"{key}: a clip for a stop registry/tours.yaml no longer has. Run scripts/narrate.py --prune")
    if OUT.exists():
        for f in sorted(OUT.rglob("*")):
            if f.is_file() and f"{f.parent.name}/{f.stem}" not in rows:
                errors.append(f"{f.relative_to(ROOT)}: a file the manifest does not list")
    trip_gate = gates.get("narration_trip_kb")
    total_gate = gates.get("narration_total_kb")
    for trip_id, size in per_trip.items():
        if trip_gate is not None and size / 1000 > trip_gate:
            errors.append(f"{trip_id}: {size / 1000:.0f} kB of Opus is over narration_trip_kb ({trip_gate})")
    if total_gate is not None and total / 1000 > total_gate:
        errors.append(f"narration is {total / 1000:.0f} kB in all, over narration_total_kb ({total_gate})")
    if errors:
        print("narration is NOT current:\n  " + "\n  ".join(errors))
        return 1
    seconds = sum(float(r.get("seconds") or 0) for r in rows.values())
    print(f"narration is current ({len(rows)} clips, {seconds / 60:.1f} min, {total / 1000:.0f} kB, "
          f"largest trip {max(per_trip.values()) / 1000:.0f} kB of Opus)")
    return 0


# --------------------------------------------------------------------------------------- render

def run(cmd: list) -> str:
    p = subprocess.run(cmd, capture_output=True, text=True)
    if p.returncode != 0:
        sys.exit(f"ffmpeg failed: {' '.join(map(str, cmd))}\n{p.stderr[-2000:]}")
    return p.stderr


def loudness(ff: str, path: Path) -> tuple:
    """Integrated loudness (LUFS) and true peak (dBTP), from ffmpeg's ebur128."""
    err = run([ff, "-hide_banner", "-nostats", "-i", str(path), "-af", "ebur128=peak=true", "-f", "null", "-"])
    tail = err[err.rfind("Summary:"):]
    i = float(re.search(r"I:\s+(-?[\d.]+) LUFS", tail).group(1))
    peak = float(re.search(r"Peak:\s+(-?[\d.inf]+) dBFS", tail).group(1))
    return i, peak


def volume(ff: str, path: Path) -> tuple:
    err = run([ff, "-hide_banner", "-nostats", "-i", str(path), "-af", "volumedetect", "-f", "null", "-"])
    mean = float(re.search(r"mean_volume: (-?[\d.]+) dB", err).group(1))
    peak = float(re.search(r"max_volume: (-?[\d.]+) dB", err).group(1))
    return mean, peak


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


class Voice:
    """The model, loaded once. Everything that needs the TTS venv is imported here and not above."""

    def __init__(self, cfg: dict, models: Path):
        import importlib.metadata as md

        engine = cfg["engine"]
        for name in ("model", "voices"):
            f = models / engine[name]["file"]
            if not f.exists():
                sys.exit(f"{f} not found; download it from {engine[name]['url']}")
            got = sha256(f)
            if got != engine[name]["sha256"]:
                sys.exit(f"{f.name}: sha256 {got} is not the one registry/narration.yaml records. A different "
                         f"model is a different voice: change engine.id and render everything again.")
        for pkg, want in (engine.get("packages") or {}).items():
            have = md.version(pkg)
            if have != str(want):
                sys.exit(f"{pkg} {have} is installed and registry/narration.yaml says {want}. A different "
                         f"version may say a word differently: pin it, or change engine.id and render again.")
        # espeak-ng keeps its data path in a 160-byte buffer and silently falls back to the path
        # it was compiled with when ours is longer, which on a deep venv is every time.
        if "ESPEAK_DATA_PATH" not in os.environ:
            import espeakng_loader
            data = Path(espeakng_loader.get_data_path()).parent
            if len(str(data)) > 120:
                link = Path(tempfile.mkdtemp(prefix="espk")) / "d"
                link.symlink_to(data)
                data = link
            os.environ["ESPEAK_DATA_PATH"] = str(data)
        import numpy as np
        from kokoro_onnx import Kokoro
        from misaki import en, espeak

        british = str(cfg["voice"]["lang"]).lower() == "en-gb"
        self.np = np
        self.g2p = en.G2P(trf=False, british=british, fallback=espeak.EspeakFallback(british=british))
        self.kokoro = Kokoro(str(models / engine["model"]["file"]), str(models / engine["voices"]["file"]))
        self.cfg = cfg

    def phonemes(self, marked: str) -> str:
        ph, _ = self.g2p(marked)
        return ph

    def say(self, marked: str, voice_id: str | None = None):
        """One sentence -> float32 samples at 24 kHz, trimmed to the speech, edges faded."""
        np = self.np
        v = self.cfg["voice"]
        audio, rate = self.kokoro.create(
            self.phonemes(marked), voice=voice_id or v["id"], speed=float(v["speed"]), lang=v["lang"],
            is_phonemes=True, trim=False, sentence_pause=0, clause_pause=0,
        )
        audio = np.asarray(audio, dtype=np.float32).reshape(-1)
        loud = np.flatnonzero(np.abs(audio) > 0.004)
        if loud.size:
            pad = int(rate * 0.03)
            audio = audio[max(0, loud[0] - pad): min(audio.size, loud[-1] + pad)]
        fade = int(rate * 0.008)
        if audio.size > 2 * fade:
            ramp = np.linspace(0, 1, fade, dtype=np.float32)
            audio[:fade] *= ramp
            audio[-fade:] *= ramp[::-1]
        return audio, rate

    def clip(self, cues: list, has_title: bool, voice_id: str | None = None):
        """All the sentences of a stop, joined with the registry's pauses. -> samples, rate, timings."""
        np = self.np
        t = self.cfg["timing"]
        rate = 24000
        parts = [np.zeros(int(rate * t["lead_s"]), dtype=np.float32)]
        timed = []
        at = float(t["lead_s"])
        for i, (shown, marked) in enumerate(cues):
            audio, rate = self.say(marked, voice_id)
            timed.append((at, at + audio.size / rate, shown))
            parts.append(audio)
            at += audio.size / rate
            last = i == len(cues) - 1
            gap = t["tail_s"] if last else (t["title_gap_s"] if has_title and i == 0 else t["gap_s"])
            parts.append(np.zeros(int(rate * gap), dtype=np.float32))
            at += int(rate * gap) / rate
        return np.concatenate(parts), rate, timed


def encode(ff: str, aac: str, wav: Path, cfg: dict, opus: Path, m4a: Path) -> dict:
    enc = cfg["encode"]
    target = float(enc["lufs"])
    ceiling = 10 ** (float(enc["peak_dbfs"]) / 20)
    lufs, _ = loudness(ff, wav)
    gain = target - lufs
    levelled = wav.with_name("levelled.wav")
    # A synthetic voice has a few tall peaks and a quiet body: a plain gain to -16 LUFS would clip
    # them by 2 to 5 dB. So the gain, then a look-ahead limiter at the ceiling, then the gain once
    # more by what the limiter took. Two rounds land within 0.3 LU; the check below holds the rest.
    for _ in range(3):
        af = f"volume={gain:.2f}dB,alimiter=limit={ceiling:.4f}:level=disabled:attack=5:release=80"
        run([ff, "-hide_banner", "-y", "-i", str(wav), "-af", af, "-ar", "48000", "-ac", "1",
             "-c:a", "pcm_s24le", str(levelled)])
        got, _ = loudness(ff, levelled)
        if abs(got - target) <= 0.2:
            break
        gain += target - got
    opus.parent.mkdir(parents=True, exist_ok=True)
    run([ff, "-hide_banner", "-y", "-i", str(levelled), "-c:a", "libopus",
         "-b:a", f"{enc['opus_kbps']}k", "-vbr", "on", "-application", "audio", "-map_metadata", "-1",
         "-fflags", "+bitexact", "-flags:a", "+bitexact", str(opus)])
    run([ff, "-hide_banner", "-y", "-i", str(levelled), "-ar", str(enc["aac_rate"]), "-c:a", aac,
         "-b:a", f"{enc['aac_kbps']}k", "-map_metadata", "-1", "-movflags", "+faststart",
         "-fflags", "+bitexact", str(m4a)])
    after, after_peak = loudness(ff, opus)
    twin, _ = loudness(ff, m4a)
    mean, vmax = volume(ff, opus)
    return {"lufs": round(after, 1), "twin_lufs": round(twin, 1), "peak": after_peak, "mean_db": mean,
            "max_db": vmax, "gain": round(gain, 2)}


def render(args) -> int:
    head, cfg = load_config()
    tours = load_tours()
    ff = args.ffmpeg
    encoders = run([ff, "-hide_banner", "-encoders"]) + subprocess.run(
        [ff, "-hide_banner", "-encoders"], capture_output=True, text=True).stdout
    if " libopus " not in encoders:
        sys.exit(f"{ff} has no libopus encoder")
    aac = "aac_at" if " aac_at " in encoders else "aac"
    import soundfile as sf

    rows = {f"{r['trip']}/{r['stop']}": r for r in cfg.get("clips") or []}
    todo = []
    live = set()
    for trip, stop in every_stop(tours):
        key = f"{trip['id']}/{stop['id']}"
        live.add(key)
        if args.only and not (key == args.only or trip["id"] == args.only):
            continue
        cues = cues_for(trip, stop, cfg)
        h = clip_hash(cues, cfg)
        p = paths(trip["id"], stop["id"])
        fresh = key in rows and rows[key].get("hash") == h and all(f.exists() for f in p.values())
        if args.force or not fresh:
            todo.append((trip, stop, key, cues, h, p))
    if args.prune:
        for key in [k for k in rows if k not in live]:
            trip_id, stop_id = key.split("/")
            for f in paths(trip_id, stop_id).values():
                if f.exists():
                    f.unlink()
            del rows[key]
            print(f"pruned {key}")
    print(f"{len(todo)} of {len(live)} stops to render")
    if todo and args.limit:
        todo = todo[: args.limit]
    voice = Voice(cfg, Path(args.models)) if todo else None
    checks = cfg.get("checks") or {}
    bad = 0
    with tempfile.TemporaryDirectory() as tmp:
        for trip, stop, key, cues, h, p in todo:
            has_title = key not in (cfg.get("skip_title") or []) and key not in (cfg.get("say") or {})
            audio, rate, timed = voice.clip(cues, has_title)
            wav = Path(tmp) / "clip.wav"
            sf.write(str(wav), audio, rate, subtype="FLOAT")
            stats = encode(ff, aac, wav, cfg, p["opus"], p["m4a"])
            p["vtt"].write_text(vtt_text(timed), encoding="utf-8")
            seconds = round(audio.size / rate, 2)
            words = word_count(cues)
            wpm = words / seconds * 60
            rows[key] = {
                "trip": trip["id"], "stop": stop["id"], "hash": h, "seconds": seconds, "words": words,
                "lufs": stats["lufs"], "opus": p["opus"].stat().st_size, "m4a": p["m4a"].stat().st_size,
                "vtt": p["vtt"].stat().st_size,
            }
            lo, hi = checks.get("wpm", [110, 200])
            problems = []
            if not lo <= wpm <= hi:
                problems.append(f"{wpm:.0f} wpm outside {lo}-{hi}")
            for name in ("lufs", "twin_lufs"):
                if abs(stats[name] - float(cfg["encode"]["lufs"])) > float(checks.get("lufs_tolerance", 1.0)):
                    problems.append(f"{name} {stats[name]}")
            if stats["mean_db"] < float(checks.get("mean_db_floor", -40)) or stats["max_db"] < float(checks.get("max_db_floor", -12)):
                problems.append(f"near silent (mean {stats['mean_db']} dB, max {stats['max_db']} dB)")
            bad += 1 if problems else 0
            print(f"{'BAD ' if problems else 'ok  '}{key}: {seconds:.1f} s, {words} words, {wpm:.0f} wpm, "
                  f"{stats['lufs']} LUFS, peak {stats['peak']} dBFS, {rows[key]['opus'] / 1000:.1f} kB opus, "
                  f"{rows[key]['m4a'] / 1000:.1f} kB m4a{' -- ' + '; '.join(problems) if problems else ''}", flush=True)
            # After every clip, so a render that is interrupted keeps what it finished.
            order = [k for k in (f"{t['id']}/{s['id']}" for t, s in every_stop(tours)) if k in rows]
            write_registry(head, [rows[k] for k in order])
    if not todo:
        order = [k for k in (f"{t['id']}/{s['id']}" for t, s in every_stop(tours)) if k in rows]
        write_registry(head, [rows[k] for k in order])
    mirror = subprocess.run([sys.executable, str(ROOT / "scripts" / "gen_narration_js.py")], capture_output=True, text=True)
    print(mirror.stdout.strip() or mirror.stderr.strip())
    return 1 if bad else 0


def audition(args) -> int:
    """The same stops in several voices, into a folder outside the repository, for a listening test."""
    _, cfg = load_config()
    tours = load_tours()
    import soundfile as sf

    out = Path(args.audition)
    out.mkdir(parents=True, exist_ok=True)
    voice = Voice(cfg, Path(args.models))
    want = set((args.stops or "people-in-space/tiangong,to-the-edge/sirius,moon-landings/surveyor-1").split(","))
    with tempfile.TemporaryDirectory() as tmp:
        for trip, stop in every_stop(tours):
            key = f"{trip['id']}/{stop['id']}"
            if key not in want:
                continue
            cues = cues_for(trip, stop, cfg)
            for vid in args.voices.split(","):
                audio, rate, _ = voice.clip(cues, True, vid)
                wav = Path(tmp) / "a.wav"
                sf.write(str(wav), audio, rate, subtype="FLOAT")
                dest = out / f"{trip['id']}--{stop['id']}--{vid}.m4a"
                encode(args.ffmpeg, "aac", wav, cfg, Path(tmp) / "a.opus", dest)
                print(f"wrote {dest}", flush=True)
    return 0


def main(argv: list) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--check", action="store_true", help="verify the manifest, the files and the budgets; no TTS")
    ap.add_argument("--script", action="store_true", help="print what the voice is given for every stop; no TTS")
    ap.add_argument("--phonemes", action="store_true", help="with --script, the phonemes too (needs the TTS venv)")
    ap.add_argument("--models", default=os.environ.get("KOKORO_MODELS", "."), help="folder with the model files")
    ap.add_argument("--ffmpeg", default=shutil.which("ffmpeg") or "ffmpeg")
    ap.add_argument("--only", help="a trip id, or trip/stop")
    ap.add_argument("--force", action="store_true", help="render even what is current")
    ap.add_argument("--limit", type=int, default=0, help="render at most this many clips this run")
    ap.add_argument("--prune", action="store_true", help="delete clips whose stop is gone")
    ap.add_argument("--audition", help="write a listening set to this folder instead of rendering")
    ap.add_argument("--voices", default="bf_emma,bm_george,af_heart,am_michael")
    ap.add_argument("--stops", help="with --audition: comma-separated trip/stop keys")
    args = ap.parse_args(argv)
    if args.check:
        return check()
    if args.script:
        _, cfg = load_config()
        voice = Voice(cfg, Path(args.models)) if args.phonemes else None
        for trip, stop in every_stop(load_tours()):
            if args.only and not (f"{trip['id']}/{stop['id']}" == args.only or trip["id"] == args.only):
                continue
            print(f"## {trip['id']}/{stop['id']}")
            for _, marked in cues_for(trip, stop, cfg):
                print("   " + marked)
                if voice:
                    print("     " + voice.phonemes(marked))
        return 0
    if args.audition:
        return audition(args)
    return render(args)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
